### ISSUE TITLE
[Question] How to add mods 

### ISSUE THREAD

**Issue by ThePandaGameMax** [Hexeption/MCP-Reborn#124]
In the description is says "for making modded clients" and "It is based on MCPConfig and ForgeGradle".

So my question is how do I add a mod for example [JEI 1.16.5](https://github.com/mezz/JustEnoughItems/tree/1.16) if I have the source code.

I tried researching it but no results. So I came here as a last resort

**Comment by Florian-Mahlberg** [comment]
I am not an expert on this, so do not trust me, but JEI is a Mod. You have just decompiled an orginal Java client. To run Mods like JEI you need Libarys. Thats why you start normally a Forge to use JEI. Forge was created to use easy external Mods. So you can not just copy the code of JEI, because you need more than just a orginal client. If you want to add something like JEI you need to start from scratch and can not use source code of Forge Mods.
