### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by AquaNot** [Hexeption/MCP-Reborn#248]
Hey ik this is a dumb af question but is there a fabric version of this?? im trying to code something in fabric using yarn mappings instead of forge and forge is kinda hard for me

**Comment by halotroop2288** [comment]
Never title your issues like this.

What you want is Yarn, not Fabric. Fabric is a name shared by the loader and the API, not the mappings.

I've been searching for something similar as well, but as far as I can tell this is as close as you can get until someone picks up the YarnForge Plugin project again and updates it to ForgeGradle 6 / NeoGradle. Parchment provides the closest thing, with their mappings provider in Librarian, and it can probably be adapted to load Yarn mappings since they both use the Tiny format. But someone is going to have to fork it and put in the work themself.
