### ISSUE TITLE
It is legal to create clients with MCP reburn?

### ISSUE THREAD

**Issue by MrAn0nym** [Hexeption/MCP-Reborn#32]

**Comment by mememasterlord32345** [comment]
yes it is legal

**Comment by gitvika** [comment]
I'm pretty sure it's legal, as long as you follow the Minecraft EULA. If you're creating your own "launcher" or something, I'm pretty sure you cannot do that. However, if it's a hacked client or something, or maybe just a regular client, it's completely fine. Also, don't post the source code on GitHub or anywhere, because it's not legal to do that.

**Comment by Toshimichi0915** [comment]
Yes
