### ISSUE TITLE
Most function names arent decompiled and/or just arent readable at all

### ISSUE THREAD

**Issue by skylerspark** [Hexeption/MCP-Reborn#35]
Most of the function names are all screwed up and seem not decompiled

They look like this:
![Capture](https://user-images.githubusercontent.com/44554976/84009629-8e160e80-a941-11ea-9889-34da99d36261.PNG)

In all the tutorials and videos Ive seen, most of these functions, arguments and variables have readable names.

I cant understand half of whats going on here... did I do something wrong? I followed the tutorial On your README.md + https://www.youtube.com/watch?v=gbr3Hhjmh8g

**Comment by balaramsudip** [comment]
MCP for latest versions have habits of doing that. The forge mdk is one example

**Comment by cosmicdan** [comment]
If you use Forge MDK you will see the same thing a lot because this isn't a bug or problem, it just means these names haven't been deobfuscated yet.

The videos you mention which don't appear to have this problem must be for a different version of MC - likely an older version with more complete mappings.

Try getting the latest mappings from MCP Bot maybe, but if you're expecting 1.15.2 to be as complete as 1.14 or 1.12 then that probably is not the case.
