### ISSUE TITLE
MCP doesn't work with launcher

### ISSUE THREAD

**Issue by StackOverDani** [Hexeption/MCP-Reborn#41]
Hello, i just built my version of mcp and i put it in the version folder with the json
[mcp.log](https://github.com/Hexeption/MCP-Reborn/files/4873486/mcp.log)
if i start the project with intellij run it works fine, but when i try to run the jar by the launcher it gives me this error and the client crash:
java.lang.ExceptionInInitializerError
> 	at net.minecraft.client.resources.DownloadingPackFinder.<init>(DownloadingPackFinder.java:62)
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:367)
> 	at net.minecraft.client.main.Main.main(Main.java:160)
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.resources.VanillaPack.lambda$static$0(VanillaPack.java:44)
> 	at net.minecraft.util.Util.make(Util.java:281)
> 	at net.minecraft.resources.VanillaPack.<clinit>(VanillaPack.java:38)
> 	... 3 more

**Comment by Florian7T** [comment]
I have this issue too 
[crash-2020-07-08_20.27.07-client.txt](https://github.com/Hexeption/MCP-Reborn/files/4892553/crash-2020-07-08_20.27.07-client.txt)
This is the crash txt
Line 369: this.packFinder = new DownloadingPackFinder(new File(this.gameDir, "server-resource-packs"), gameConfig.folderInfo.getAssetsIndex());

**Comment by Florian7T** [comment]
I fixed it by using the "data" and "assets" folder from the 1.16.1 Optifine client into mine. Though i believe that the assets and data folder from the normal client or any (working) client works too. The error was caused by the class VanillaPack not finding the internal vanilla resourcepack which is in the "data" and "assets folder". You can drag these folders into your client using WinRaR. 
![Screenshot_4](https://user-images.githubusercontent.com/68027868/87061694-5d5d1980-c20c-11ea-812d-c332a87daa2a.png)

**Comment by balaramsudip** [comment]
How do you run it through the launcher?

**Comment by Florian7T** [comment]
> How do you run it through the launcher?

To run the client you'll have to make a folder with exactly the same name as your jar in the .minecraft/versions folder
Then put your jar into that folder and make a json file with the same name as your folder and jar
That json needs certain information but there's a python script on github that makes one for you.
The info it needs but not all info is a must have: https://minecraft.gamepedia.com/Client.json

Json maker:  https://github.com/m-kypr/client-json
