### ISSUE TITLE
I can't run it in the launcher!

### ISSUE THREAD

**Issue by l-7777777** [Hexeption/MCP-Reborn#72]
When I try to run my built jar in the launcher, it gives me this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
  at net.minecraft.client.main.Main.main(Main.java:63)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 1 more
Process crashed with exit code 1
```

[Here](https://drive.google.com/drive/folders/1xXXpawp6mRb4k_NqOWiK_iDj4gxKuugx?usp=sharing) is my version folder.

**Comment by Meloeguy** [comment]
> When I try to run my built jar in the launcher, it gives me this:
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
>   at net.minecraft.client.main.Main.main(Main.java:63)
> Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 1 more
> Process crashed with exit code 1
> ```
> 
> [Here](https://drive.google.com/drive/folders/1xXXpawp6mRb4k_NqOWiK_iDj4gxKuugx?usp=sharing) is my version folder.

I had a similar issue and I think I have a solution.  (Sorry for grammer and spelling mistakes)

1. Try to re-install the mcp-reborn version in a totaly new workspace properly. Make sure there are no errors in the code.
2. Make sure you compile it on javaSE 12.
3. Build the mcp-reborn and find your compiled/exported .jar file properly - no mistakes or errors.
4. Open the mcp.jar compiled file with winrar/winzip and delete META-INF from it.
5. Open the client-extra.jar file using winrar\winzip in this path: 
    "C:\Users\"YOUR USER"\.gradle\caches\forge_gradle\minecraft_repo\versions\1.16.3".
6. Copy all the files but META-INF and paste it in your compiled mcp-reborn ".jar" file
7. Then you have your custom version ready properly, just need to create custom launcher (Nice youtube tutorial: https://www.youtube.com/watch?v=DN3-ZWfuPNc&list=PLAHsHCEJMTE0KgzVKYbXo-XQCT-mwkB1G&index=116&ab_channel=KinderrKill-D%C3%A9veloppementMinecraft)
8. when you add your custom version make sure you don't use the defult JAVA EXECUTABLE javaw.exe path. That's because the defult java is version 8/1.8.0. Find your jdk 12 or above (The path for me: C:\Program Files\Java\jdk-14.0.2\bin) and run minecraft using this. 
 
I had a similar issue, doing this solved the error. Now I am playing single player minecraft with my custom made minecraft mods.

**Comment by minecraft3r217** [comment]
where might you find the mcp.jar?

**Comment by Meloeguy** [comment]
> where might you find the mcp.jar?

In your mcp folder, go to build, libs and there after you have built your project, you will have "mcp-reborn-1.0.0.jar" file. For me: C:\MCP-reborn-1.16\build\libs

**Comment by l-7777777** [comment]
I found that MultiMC's "Add to Minecraft.jar" option does all of this for you.
